"""Playable presentation demo for Chess Psych.

Run:
    streamlit run apps/presentation_demo.py
"""
import time
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

import chess
import streamlit as st
import streamlit.components.v1 as components

from chess_psych.config import config
from chess_psych.live_coach import LiveCoach, Pattern
from chess_psych.stockfish_pool import StockfishPool

st.set_page_config(page_title="Chess Psych — Demo", layout="wide")

# --- Styling (Light Mode & Toasts) ---
st.markdown("""
<style>
    .main { background: #f8fafc; color: #1e293b; }
    section[data-testid="stSidebar"] { background: #f1f5f9; border-right: 1px solid #e2e8f0; }
    h1, h2, h3 { color: #0f172a; }
    .pattern-card { background: #ffffff; border-left: 4px solid #6366f1;
                    padding: 10px 12px; border-radius: 6px; margin-bottom: 8px;
                    border: 1px solid #e2e8f0; box-shadow: 0 1px 2px rgba(0,0,0,0.05); }
    .verdict-critical { background: #fef2f2; border-left: 4px solid #ef4444;
                        color: #991b1b; padding: 12px; border-radius: 6px; margin-bottom: 6px; }
    .verdict-warning  { background: #fffbeb; border-left: 4px solid #f59e0b;
                        color: #92400e; padding: 12px; border-radius: 6px; margin-bottom: 6px; }
    .verdict-info     { background: #eff6ff; border-left: 4px solid #3b82f6;
                        color: #1e40af; padding: 12px; border-radius: 6px; margin-bottom: 6px; }
    .verdict-move { font-weight: 600; color: #0f172a; }
    .verdict-meta { font-size: 0.75rem; opacity: 0.8; color: #64748b;}
</style>
""", unsafe_allow_html=True)

# --- State Init ---
if "demo_sf" not in st.session_state:
    st.session_state.demo_sf = StockfishPool()
    st.session_state.demo_sf.start()

defaults = {
    "chess_board": chess.Board(), "move_history": [], "verdicts": [],
    "last_move_ts": None, "game_over": False, "demo_rating": 1300
}
for k, v in defaults.items():
    if k not in st.session_state:
        st.session_state[k] = v

# --- Hijacked Coach Logic ---
def get_demo_coach(rating: int) -> LiveCoach:
    """Creates a mock coach that forces a pattern match for the 2100 profile on ANY blunder."""
    sf = st.session_state.demo_sf
    
    if rating == 1300:
        return LiveCoach(1, "Demo_1300", 1300, [], None, sf)
    
    # 2100 Profile setup
    pattern = Pattern(
        pattern_id=99, cluster_id=99, name="Premature Tension Release",
        description="Liquidates central tension too early, handing over the initiative. Typical when facing complex calculations.",
        size=12, centroid=None
    )
    coach = LiveCoach(2, "Demo_2100", 2100, [pattern], None, sf)
    
    # Monkey-patch the matcher: if a move is a blunder, ALWAYS match the pattern
    coach._match_pattern = lambda vec: (pattern, 0.88) 
    return coach

# --- Sidebar UI ---
with st.sidebar:
    st.markdown("## 🎭 Presentation Mode")
    st.caption("Toggle the active profile mid-game to show dynamic thresholding.")
    
    selected_rating = st.radio("Active Profile", [1300, 2100], 
                               format_func=lambda x: f"Intermediate ({x})" if x == 1300 else f"Master ({x})")
    st.session_state.demo_rating = selected_rating
    
    st.divider()
    if st.button("▶ Reset Board", use_container_width=True, type="primary"):
        st.session_state.chess_board = chess.Board()
        st.session_state.move_history = []
        st.session_state.verdicts = []
        st.rerun()

# --- Board Component (Imported exactly as in app.py) ---
def board_component():
    component_dir = REPO_ROOT / "web_components" / "chessboard"
    component_dir.mkdir(exist_ok=True)
    html_path = component_dir / "index.html"
    
    # Standard chessboard.js HTML (Assuming it's already generated by app.py)
    if not html_path.exists():
        st.error("Please run apps/live_coach_app.py once first to generate the board HTML.")
        return None
        
    _component = components.declare_component("chess_board", path=str(component_dir))
    return _component(
        fen=st.session_state.chess_board.fen(),
        orientation="white",
        position_id=len(st.session_state.move_history),
        key="board_widget",
    )

# --- Move Pipeline ---
def process_user_move(move_uci: str):
    board = st.session_state.chess_board
    try:
        move = chess.Move.from_uci(move_uci)
    except ValueError:
        return
    if move not in board.legal_moves:
        promo = chess.Move.from_uci(move_uci + "q")
        if promo in board.legal_moves: move = promo
        else: return

    board_before = board.copy()
    san = board.san(move)
    board.push(move)

    # Instantiate the coach on the fly based on the sidebar toggle
    coach = get_demo_coach(st.session_state.demo_rating)
    verdict = coach.evaluate_move(board_before, move, board, time_spent=2.0)
    
    st.session_state.move_history.append({"side": "user", "san": san, "uci": move.uci()})
    st.session_state.verdicts.append(verdict)

    # Real-time UI Popups
    if verdict.severity == "critical":
        st.toast(f"🚨 Pattern Matched: {verdict.matched_pattern.name}", icon="🚨")
    elif verdict.severity == "warning":
        st.toast("⚠️ Significant evaluation drop detected.", icon="⚠️")

    if not board.is_game_over():
        sf = st.session_state.demo_sf
        result = sf.play(board, depth=8) # Lower depth for faster demo response
        if result.move:
            engine_san = board.san(result.move)
            board.push(result.move)
            st.session_state.move_history.append({"side": "engine", "san": engine_san, "uci": result.move.uci()})

# --- Layout ---
col_board, col_coach = st.columns([1.4, 1])

with col_board:
    st.markdown(f"## Playing as: **{st.session_state.demo_rating}**")
    move = board_component()
    if move and isinstance(move, dict) and "move" in move:
        last_handled = st.session_state.get("_last_handled_move")
        move_key = (move.get("move"), move.get("ts"))
        if move_key != last_handled:
            st.session_state["_last_handled_move"] = move_key
            process_user_move(move["move"])
            st.rerun()

with col_coach:
    st.markdown("### 🧠 Live Analysis")
    if not st.session_state.move_history:
        st.caption("Play a move to begin real-time behavioral monitoring.")
    
    verdict_iter = iter(st.session_state.verdicts)
    items = []
    for i, mv in enumerate(st.session_state.move_history):
        if mv["side"] == "user":
            try: v = next(verdict_iter)
            except StopIteration: v = None
            items.append(("user", i, mv, v))
        else:
            items.append(("engine", i, mv, None))

    for kind, idx, mv, v in reversed(items[-6:]):
        if kind == "user" and v is not None:
            cls = f"verdict-{v.severity}"
            meta = f" • match {v.similarity:.2f}" if v.matched_pattern else ""
            message = v.coach_note or v.headline
            st.markdown(f"""
            <div class="{cls}">
                <div class="verdict-move">▶ You: {mv['san']}</div>
                <div>{message}</div>
                <div class="verdict-meta">move {idx // 2 + 1}{meta}</div>
            </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown(f"""
            <div style="opacity: 0.6; padding: 4px 12px; font-size: 0.85rem; color: #64748b; margin-bottom: 6px;">
                ◇ Engine: {mv['san']}
            </div>
            """, unsafe_allow_html=True)
